services:
  postgres:
    image: postgres:16
    container_name: ai-postgres
    environment:
      POSTGRES_DB: ai_internship
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres@1234
    ports:
      - "5432:5432"
